### ISSUE TITLE
DBEnum doesn't work for sqlite

### ISSUE THREAD

**Issue by ghost** [behos/models-derive#2]
```
error[E0271]: type mismatch resolving `<diesel::sqlite::Sqlite as diesel::backend::Backend>::RawValue == [u8]`
```

and

```
    = note: expected type `diesel::sqlite::connection::sqlite_value::SqliteValue`found type `[u8]`
```

**Comment by behos** [comment]
Thanks for reporting this isue. I'm afraid that I won't be maintaining this crate any more since there are more active alternatives around (for example https://crates.io/crates/diesel-derive-enum) addressing each of the features in separate packages.
